language: python

python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
  - 3.10

before_install:
  - sudo apt-get update
  - python3 -m pip install pylint pytest

install:
  - make install

script:
  - make test
  - make lint
  - make coverage
